### ISSUE TITLE
crash with google chrome on ubuntu

### ISSUE THREAD

**Issue by DarianEnriqueMartinezPombar** [kde-yyds/kwin4_effects_foldpopups#1]
The truth is very good but it fails me with google chrome, it unfolds well downwards but when it closes there is a bad visual effect, it only happens with google chrome, if you could fix it please.

**Comment by kde-yyds** [comment]
could you please upload a video? It works well with my chromium

**Comment by DarianEnriqueMartinezPombar** [comment]
as I was saying, it only happens to me in google chrome, video:
https://drive.google.com/file/d/1lHQVWWmrITXojOVBeiyj5FDUxYPIgeig/view?usp=sharing

**Comment by kde-yyds** [comment]
Can you upload this video directly in Github?It is not allowed to acces to google in China

**Comment by DarianEnriqueMartinezPombar** [comment]
https://user-images.githubusercontent.com/70375296/192242840-6fe63231-a3c4-4d9c-9ecb-b58375467ff0.mp4

**Comment by kde-yyds** [comment]
https://user-images.githubusercontent.com/106876912/193284156-bc92dbd8-a607-46d2-9528-d483cafb1dc1.mp4

Which version of plasma do you use?

**Comment by DarianEnriqueMartinezPombar** [comment]
![2022-10-03_09-16](https://user-images.githubusercontent.com/70375296/193520815-580b4b1c-cce6-464d-a6ba-c5cd229f7e83.png)

**Comment by kde-yyds** [comment]
![Screenshot_20221004_123038](https://user-images.githubusercontent.com/106876912/193734612-39cf8314-ffdc-4190-ae97-9350fb5b4c1b.png)

**Comment by kde-yyds** [comment]
> ![2022-10-03_09-16](https://user-images.githubusercontent.com/70375296/193520815-580b4b1c-cce6-464d-a6ba-c5cd229f7e83.png)

Can you try to create a new user and try with the new one?

**Comment by kde-yyds** [comment]
I tried kubuntu 21.04, it can't work properly on chromium adn other gtk-based programs.
Can you try to update to kubuntu 22.10?

**Comment by kde-yyds** [comment]
https://user-images.githubusercontent.com/106876912/193976712-7d362eaa-a96c-4412-8714-f4134d3a28fa.mp4

I tried kubuntu 21.04, it can't work properly on chromium and other gtk-based programs.
Can you try to update to kubuntu 22.10?

**Comment by DarianEnriqueMartinezPombar** [comment]
ubuntu 22.04 does not have version 5.25 of kde available, now on October 20 I update to version 22.10 that already comes with kde 5.25, but on the extension page you should put that it only works for version of kde 5.25 like the other extensions have it, thank you very much anyway.

**Comment by kde-yyds** [comment]
I fixed it in c0b5137f44dada16b7f1115e0474cad291eddeec
