### ISSUE TITLE
Is it possible to add fcitx5 to the blacklist?

### ISSUE THREAD

**Issue by MOldtime** [kde-yyds/kwin4_effects_foldpopups#12]
https://github.com/kde-yyds/kwin4_effects_foldpopups/assets/38435967/944ecee4-b0d9-40c5-a4a8-432eb6f024e5

**Comment by kde-yyds** [comment]
I can also reproduce this. I will try it later

**Comment by kde-yyds** [comment]
哪儿来的qq圆角(doge

**Comment by MOldtime** [comment]
> 哪儿来的qq圆角(doge

https://github.com/a-parhom/LightlyShaders/tree/plasma6

**Comment by kde-yyds** [comment]
> > 哪儿来的qq圆角(doge
> 
> https://github.com/a-parhom/LightlyShaders/tree/plasma6

thanks

**Comment by kde-yyds** [comment]
0bb63764b71058641069af0ad91a26cc2cbb02c9  
i tried to add it to blacklist, but it only works on x11 and Xwayland.

**Comment by MOldtime** [comment]
感谢修复
