### ISSUE TITLE
Feature request: Fold upwards if the cursor is closer to the bottom of the popup than the top

### ISSUE THREAD

**Issue by HugLifeTiZ** [kde-yyds/kwin4_effects_foldpopups#2]
Hi there. Very neat effect! I'm happily using it on my system. It looks very slick!

I think a subtle touch that would make it even slicker is that when a popup menu appears with its bottom edge closer to the cursor than the top, like when you right click at the bottom of the screen, the fold direction is inverted so that it folds up from the cursor rather than down *toward* the cursor, as it currently works.

**Comment by kde-yyds** [comment]
> 

Do you know how to get cursor's location and screen resolution in js?

**Comment by HugLifeTiZ** [comment]
Sorry, I don't know any programming specifics for KWin effects. However, I don't think you would need the screen resolution. Just the location of the bottom edge of the window. If the cursor location is within, say, 4 pixels of the bottom edge, the fold should go in the opposite direction.

I guess what you would do, in some really crude pseudo code:

```
if (cursor.x > (popup.x - 4) && cursor.x < (popup.x + popup.width + 4) &&
  cursor.y > (popup.y + popup.height - 4) && cursor.y < (popup.y + popup.height + 4)) {
    // flip the animation
}
```

**Comment by kde-yyds** [comment]
> Sorry, I don't know any programming specifics for KWin effects. However, I don't think you would need the screen resolution. Just the location of the bottom edge of the window. If the cursor location is within, say, 4 pixels of the bottom edge, the fold should go in the opposite direction.
> 
> I guess what you would do, in some really crude pseudo code:
> 
> ```
> if (cursor.x > (popup.x - 4) && cursor.x < (popup.x + popup.width + 4) &&
>   cursor.y > (popup.y + popup.height - 4) && cursor.y < (popup.y + popup.height + 4)) {
>     // flip the animation
> }
> ```

I will try it later

**Comment by kde-yyds** [comment]
> Sorry, I don't know any programming specifics for KWin effects. However, I don't think you would need the screen resolution. Just the location of the bottom edge of the window. If the cursor location is within, say, 4 pixels of the bottom edge, the fold should go in the opposite direction.
> 
> I guess what you would do, in some really crude pseudo code:
> 
> ```
> if (cursor.x > (popup.x - 4) && cursor.x < (popup.x + popup.width + 4) &&
>   cursor.y > (popup.y + popup.height - 4) && cursor.y < (popup.y + popup.height + 4)) {
>     // flip the animation
> }
> ```

<Unknown File>:81: ReferenceError: cursor is not defined

**Comment by HugLifeTiZ** [comment]
That was pseudo-code. Fake code. Like I said: I don't know how you'd get the cursor position or popup geometry. But once you do, that might be the check you'd make to determine whether to flip the animation.

**Comment by kde-yyds** [comment]
> 

I know how to get popup geometry and position,but I haven't found an api to get cursor position
