### ISSUE TITLE
The task switcher and spectacle screenshot UI probably shouldn't be folded

### ISSUE THREAD

**Issue by Void-0000** [kde-yyds/kwin4_effects_foldpopups#3]
Fullscreen task switchers like "cover switch" and spectacle's darkened screen UI when taking screenshots are also folded in and out, making them look like they're dropping down from the top of the screen. This is probably not intended and looks pretty weird.

**Comment by kde-yyds** [comment]
Do you know how to locate "cover switch" effect window?
